/**
 * End-to-end verification: walks the public site and the full publish flow,
 * screenshotting each step. Run against a server on localhost:3000.
 */
import { chromium } from "playwright";
import { mkdirSync, writeFileSync } from "fs";

const BASE = "http://localhost:3000";
const OUT = "/home/claude/shots";
mkdirSync(OUT, { recursive: true });

const problems = [];
const log = (m) => console.log(m);

const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await ctx.newPage();

page.on("console", (m) => {
  if (m.type() === "error") problems.push(`console error @ ${page.url()}: ${m.text()}`);
});
page.on("pageerror", (e) => problems.push(`page error @ ${page.url()}: ${e.message}`));
page.on("response", (r) => {
  if (r.status() >= 400 && !r.url().includes("favicon")) {
    problems.push(`HTTP ${r.status()} ${r.url()}`);
  }
});

async function shot(name, full = true) {
  await page.waitForTimeout(1200);
  await page.screenshot({ path: `${OUT}/${name}.png`, fullPage: full });
  log(`  shot ${name}`);
}

// ---------- Public site ----------
log("Public site");
await page.goto(BASE, { waitUntil: "load" });
await shot("01-home");

await page.goto(`${BASE}/story/sample-newsroom-opens`, { waitUntil: "load" });
await shot("02-story");

await page.goto(`${BASE}/section/research`, { waitUntil: "load" });
await shot("03-section");

await page.goto(`${BASE}/search?q=latency`, { waitUntil: "load" });
await shot("04-search");

await page.goto(`${BASE}/about`, { waitUntil: "load" });
await shot("05-about");

await page.goto(`${BASE}/does-not-exist`, { waitUntil: "load" });
await shot("06-404", false);

// Mobile
const mobile = await browser.newContext({
  viewport: { width: 390, height: 844 },
  isMobile: true,
  deviceScaleFactor: 2,
});
const mp = await mobile.newPage();
await mp.goto(BASE, { waitUntil: "load" });
await mp.waitForTimeout(600);
await mp.screenshot({ path: `${OUT}/07-mobile-home.png`, fullPage: true });
await mp.goto(`${BASE}/story/sample-latency-report`, { waitUntil: "load" });
await mp.waitForTimeout(600);
await mp.screenshot({ path: `${OUT}/08-mobile-story.png`, fullPage: true });
log("  shots 07-08 mobile");
await mobile.close();

// ---------- Auth gate ----------
log("Auth");
await page.goto(`${BASE}/admin`, { waitUntil: "load" });
if (!page.url().includes("/admin/login")) problems.push("!! /admin did not require sign in");
await shot("09-login", false);

// Wrong password must be rejected
await page.fill("#password", "definitely-wrong");
await page.click('button[type="submit"]');
await page.waitForTimeout(1600);
if (page.url().includes("/admin") && !page.url().includes("login")) {
  problems.push("!! wrong password was accepted");
} else {
  log("  wrong password rejected");
}

// Real sign in
await page.fill("#name", "Ben");
await page.fill("#password", "luminary");
await page.click('button[type="submit"]');
await page.waitForURL("**/admin", { timeout: 15000 });
await shot("10-desk");

// ---------- Publish flow ----------
log("Publish flow");
await page.goto(`${BASE}/admin/new`, { waitUntil: "load" });
await shot("11-editor-empty");

// Upload a .docx through the import route
await page.setInputFiles(
  'input[accept=".docx,.md,.markdown,.txt,.html,.htm"]',
  "/tmp/import-test.docx"
);
await page.waitForTimeout(2500);
const importedTitle = await page.inputValue("#title");
const importedBody = await page.inputValue("#body");
if (!importedTitle.includes("Word")) problems.push(`!! docx title not extracted (got "${importedTitle}")`);
if (!importedBody.includes("second paragraph")) problems.push("!! docx body not extracted");
if (!importedBody.includes("## A heading")) problems.push("!! docx heading not converted to markdown");
if (!importedBody.includes("**bold**")) problems.push("!! docx bold not converted");
log(`  docx import -> title: "${importedTitle}"`);
await shot("12-editor-imported");

// Cover image upload
await page.setInputFiles('aside input[accept="image/*"]', "/tmp/cover.png");
await page.waitForTimeout(2000);
const hasCover = await page.locator("aside img").count();
if (hasCover === 0) problems.push("!! cover image did not upload");
else log("  cover image uploaded");

// Fill the rest
await page.fill("#dek", "A verification story generated by the end-to-end test run.");
await page.fill("#tags", "verification, test");
await page.fill('input[name="author"]', "Ben Hizer");
await page.fill('input[name="author_title"]', "Founder");
await page.selectOption("#section", "news");
await page.fill('input[name="cover_alt"]', "A verification image");
await shot("13-editor-filled");

// Preview toggle
await page.click('button:has-text("Preview")');
await page.waitForTimeout(600);
await shot("14-editor-preview");
await page.click('button:has-text("Write")');
await page.waitForTimeout(400);

// Publish
await page.click('button:has-text("Publish")');
await page.waitForURL("**/admin/stories/**", { timeout: 20000 });
await page.waitForTimeout(800);
await shot("15-after-publish");

// Confirm it is live on the public site
await page.goto(BASE, { waitUntil: "load" });
const liveOnHome = await page.locator(`text=${importedTitle}`).count();
if (liveOnHome === 0) problems.push("!! published story does not appear on the front page");
else log("  story is live on the front page");
await shot("16-home-with-new-story");

// The cover image must actually render
const imgOk = await page.evaluate(() => {
  const imgs = Array.from(document.querySelectorAll("img"));
  return imgs.length > 0 && imgs.every((i) => i.complete && i.naturalWidth > 0);
});
if (!imgOk) problems.push("!! an image on the front page failed to load");
else log("  images render");

// ---------- Feed & sitemap ----------
log("Feed / sitemap");
const feed = await page.request.get(`${BASE}/feed.xml`);
const feedText = await feed.text();
if (!feedText.includes("<rss")) problems.push("!! feed.xml is not valid RSS");
if (!feedText.includes(importedTitle)) problems.push("!! new story missing from RSS feed");
else log("  RSS contains the new story");

const smap = await page.request.get(`${BASE}/sitemap.xml`);
const smapText = await smap.text();
if (!smapText.includes("/story/")) problems.push("!! sitemap has no story URLs");
else log("  sitemap lists stories");

// ---------- Draft stays private ----------
log("Draft privacy");
await page.goto(`${BASE}/admin/new`, { waitUntil: "load" });
await page.fill("#title", "Secret draft that must not leak");
await page.fill("#body", "This body should never be publicly reachable.");
await page.click('button:has-text("Save draft")');
await page.waitForURL("**/admin/stories/**", { timeout: 20000 });
const draftUrl = page.url();
const draftSlug = await page.inputValue("#slug");
const anon = await browser.newContext();
const ap = await anon.newPage();
const res = await ap.goto(`${BASE}/story/${draftSlug}`);
if (res && res.status() !== 404) problems.push(`!! draft is publicly readable (HTTP ${res.status()})`);
else log("  draft returns 404 publicly");
const homeAnon = await ap.goto(BASE);
const leaked = await ap.locator("text=Secret draft that must not leak").count();
if (leaked > 0) problems.push("!! draft title leaked onto the front page");
const adminAnon = await ap.goto(`${BASE}/admin`);
if (adminAnon && !adminAnon.url().includes("login")) problems.push("!! /admin reachable while signed out");
await anon.close();

// ---------- Scheduled story stays embargoed ----------
log("Scheduling");
await page.goto(`${BASE}/admin/new`, { waitUntil: "load" });
await page.fill("#title", "Embargoed until next week");
await page.fill("#body", "This must not be readable before its publish time.");
const future = new Date(Date.now() + 7 * 86400000);
const pad = (n) => String(n).padStart(2, "0");
await page.fill(
  "#published_at",
  `${future.getFullYear()}-${pad(future.getMonth() + 1)}-${pad(future.getDate())}T09:00`
);
await page.click('button:has-text("Publish")');
await page.waitForURL("**/admin/stories/**", { timeout: 20000 });
const schedUrl = page.url();
const schedSlug = await page.inputValue("#slug");
const anon2 = await browser.newContext();
const ap2 = await anon2.newPage();
const schedRes = await ap2.goto(`${BASE}/story/${schedSlug}`);
if (schedRes && schedRes.status() !== 404) {
  problems.push(`!! scheduled story readable before its time (HTTP ${schedRes.status()})`);
} else {
  log("  scheduled story 404s until its publish time");
}
await ap2.goto(BASE);
if ((await ap2.locator("text=Embargoed until next week").count()) > 0) {
  problems.push("!! scheduled story leaked onto the front page");
}
const schedFeed = await ap2.request.get(`${BASE}/feed.xml`);
if ((await schedFeed.text()).includes("Embargoed until next week")) {
  problems.push("!! scheduled story leaked into the RSS feed");
}
await anon2.close();

await page.goto(schedUrl, { waitUntil: "load" });
await page.click('button:has-text("Delete this story")');
await page.waitForTimeout(400);
await page.click('button:has-text("Yes, delete")');
await page.waitForURL("**/admin**", { timeout: 15000 });

// ---------- Clean up the test rows ----------
await page.goto(draftUrl, { waitUntil: "load" });
await page.click('button:has-text("Delete this story")');
await page.waitForTimeout(400);
await page.click('button:has-text("Yes, delete")');
await page.waitForURL("**/admin**", { timeout: 15000 });
log("  delete flow works");
await shot("17-desk-final");

writeFileSync(
  `${OUT}/report.txt`,
  problems.length ? problems.join("\n") : "No problems found."
);

log("");
if (problems.length) {
  log(`PROBLEMS (${problems.length}):`);
  problems.forEach((p) => log("  - " + p));
} else {
  log("PASS — no problems found.");
}

await browser.close();
process.exit(problems.filter((p) => p.startsWith("!!")).length ? 1 : 0);
